### ISSUE TITLE
Can't compile on Ubuntu 18.04 x64

### ISSUE THREAD

**Issue by Yume303** [bg2bhc/gr-dslwp#10]
The error message is:

[ 47%] Building CXX object lib/CMakeFiles/gnuradio-dslwp.dir/kiss_decode_pdu_impl.cc.o
[ 49%] Building CXX object lib/CMakeFiles/gnuradio-dslwp.dir/fec_encode_b_impl.cc.o
/home/yume/Projects/gr-dslwp/lib/fec_encode_b_impl.cc: In member function ‘virtual int gr::dslwp::fec_encode_b_impl::work(int, gr_vector_const_void_star&, gr_vector_void_star&)’:
/home/yume/Projects/gr-dslwp/lib/fec_encode_b_impl.cc:96:69: error: narrowing conversion of ‘254’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
  char msg_ptt_on[] = {0xFE, 0xFE, 0x7C, 0xE0, 0x1C, 0x00, 0x01, 0xFD};
                                                                     ^
/home/yume/Projects/gr-dslwp/lib/fec_encode_b_impl.cc:96:69: error: narrowing conversion of ‘254’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/yume/Projects/gr-dslwp/lib/fec_encode_b_impl.cc:96:69: error: narrowing conversion of ‘224’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/yume/Projects/gr-dslwp/lib/fec_encode_b_impl.cc:96:69: error: narrowing conversion of ‘253’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/yume/Projects/gr-dslwp/lib/fec_encode_b_impl.cc:97:70: error: narrowing conversion of ‘254’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
  char msg_ptt_off[] = {0xFE, 0xFE, 0x7C, 0xE0, 0x1C, 0x00, 0x00, 0xFD};
                                                                      ^
/home/yume/Projects/gr-dslwp/lib/fec_encode_b_impl.cc:97:70: error: narrowing conversion of ‘254’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/yume/Projects/gr-dslwp/lib/fec_encode_b_impl.cc:97:70: error: narrowing conversion of ‘224’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/yume/Projects/gr-dslwp/lib/fec_encode_b_impl.cc:97:70: error: narrowing conversion of ‘253’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
lib/CMakeFiles/gnuradio-dslwp.dir/build.make:638: recipe for target 'lib/CMakeFiles/gnuradio-dslwp.dir/fec_encode_b_impl.cc.o' failed
make[2]: *** [lib/CMakeFiles/gnuradio-dslwp.dir/fec_encode_b_impl.cc.o] Error 1
CMakeFiles/Makefile2:174: recipe for target 'lib/CMakeFiles/gnuradio-dslwp.dir/all' failed
make[1]: *** [lib/CMakeFiles/gnuradio-dslwp.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sv1** [comment]
Same problem here on Debian 9.4 (x64)...

**Comment by Kerry-Huang** [comment]
Try the lastest version.
It was fix in #6
